const portfolioProjects = [
  {
    id: 1,
    project_image: "tech_01.png",
    project_title: "Technology Blog",
    description:
      "Blog site that allows users to register, make posts, and comment.",
    repo_url: "https://github.com/levisgaragegroupinc/mvc_tech-blog",
    app_url: "https://mvc-technology-blog.herokuapp.com/",
    code_stack: [
      "HTML",
      "CSS",
      "Javascript",
      "Handlebars",
      "Express",
      "Sequelize",
      "Connect-session-sequelize",
      "MySQL2",
      "Bcrypt",
      "Heroku",
      "JAWS DB",
    ],
  },
  {
    id: 2,
    project_image: "knack_01.png",
    project_title: "Knicknacks",
    description: "A communit jobs board for everyone.",
    repo_url: "https://github.com/levisgaragegroupinc/KnickKnacks",
    app_url: "https://knickknacks-ondemand.herokuapp.com/",
    code_stack: [
      "HTML",
      "CSS",
      "Javascript",
      "Handlebars",
      "Express",
      "Sequelize",
      "Connect-session-sequelize",
      "MySQL2",
      "Bcrypt",
      "Heroku",
      "JAWS DB",
      "Trustifi",
    ],
  },
];
