const projectPortfolio = [
  {
    id: 1,
    project_image: "tech_01.png",
    project_title: "Technology Blog",
    description:
      "Blog site that allows users to register, make posts, and comment.",
    anchor_tag: "techblog",
    repo_url: "https://github.com/levisgaragegroupinc/mvc_tech-blog",
    app_url: "https://mvc-technology-blog.herokuapp.com/",
    code_stack: [
      "HTML",
      "CSS",
      "Javascript",
      "Handlebars",
      "Express",
      "Sequelize",
      "Connect-session-sequelize",
      "MySQL2",
      "Bcrypt",
      "Heroku",
      "JAWS DB",
    ],
  },
  {
    id: 2,
    project_image: "knack_01.png",
    project_title: "Knicknacks",
    description: "A communit jobs board for everyone.",
    repo_url: "https://github.com/levisgaragegroupinc/KnickKnacks",
    anchor_tag: "knickknacks",
    app_url: "https://knickknacks-ondemand.herokuapp.com/",
    code_stack: [
      "HTML",
      "CSS",
      "Javascript",
      "Handlebars",
      "Express",
      "Sequelize",
      "Connect-session-sequelize",
      "MySQL2",
      "Bcrypt",
      "Heroku",
      "JAWS DB",
      "Trustifi",
    ],
  },
  {
    id: 3,
    project_image: "wx_01.png",
    project_title: "Open Weather App",
    description: "A 5-day forecast weather app. Save locations.",
    anchor_tag: "weather",
    repo_url: "https://github.com/levisgaragegroupinc/open-weather-app",
    app_url: "https://levisgaragegroupinc.github.io/open-weather-app/",
    code_stack: ["HTML", "CSS", "Javascript", "Moment.js", "OpenWeather API"],
  },
  {
    id: 4,
    project_image: "quiz_01.png",
    project_title: "Quiz App",
    description:
      "An app that tests users knowledge of the Javascript programming language.",
    anchor_tag: "quiz",
    repo_url: "https://github.com/levisgaragegroupinc/Programming-Quiz",
    app_url: "https://levisgaragegroupinc.github.io/Programming-Quiz/",
    code_stack: ["HTML", "CSS", "Javascript"],
  },
  {
    id: 5,
    project_image: "translation_01.png",
    project_title: "Translation App",
    description: "Translate sentences from English into 17 other languages.",
    anchor_tag: "translation",
    repo_url: "https://github.com/levisgaragegroupinc/translation_app",
    app_url: "https://levisgaragegroupinc.github.io/translation_app/",
    code_stack: [
      "HTML",
      "CSS",
      "Foundation framework",
      "Javascript",
      "JQuery",
      "Google translate API",
      "Merriam-Webster's Dictionary API",
      "Merriam-Webster's Thesaurus API",
    ],
  },
  {
    id: 6,
    project_image: "notes_01.png",
    project_title: "Notes",
    description:
      "A simple note taker. Add and delete notes. Notes include title.",
    anchor_tag: "notes",
    repo_url: "https://github.com/levisgaragegroupinc/note-keeper",
    app_url: "https://glacial-plains-24658.herokuapp.com/notes",
    code_stack: [
      "HTML",
      "CSS",
      "Bootstrap framework",
      "Fontawesome",
      "Javascript",
      "Express",
      "UUID",
      "Heroku",
    ],
  },
];

export default projectPortfolio;
